name: Java CI with Gradle

on:
  push:
    branches: ["development"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Enable permissions on folder
        run: chmod +x ./gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with gradle wrapper
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Test with Gradle
        run: ./gradlew test

  push-image: # This job creates a docker image and pushes it to the GitHub Container Registry
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          ./gradlew build
          docker build . --tag ghcr.io/vicabi/grupplabb3:development
          docker push ghcr.io/vicabi/grupplabb3:development

          # Save image name to output IMAGE_NAME
          echo "::set-output name=IMAGE_NAME::ghcr.io/vicabi/grupplabb3:development"

  # Create deployment
  deploy:
    runs-on: ubuntu:latest
    needs: push-image

    steps:
      - name: Simulate deployment
        run: |
          echo "Simulated deployment of image: ${{ needs.push-image.outputs.IMAGE_NAME }}"
